### ISSUE TITLE
Template path issue when using jquery.tmpl

### ISSUE THREAD

**Issue by grofit** [ifandelse/Knockout.js-External-Template-Engine#13]
This is a follow up from the post I made in the other Template Path issue, as I was unable to reproduce it in an isolated scenario I was trying to see what specifically in my source code could cause the external template engine vars to be ignored within the data-bind.

Anyway I have found the issue, or believe I have. After a few hours of pulling things in and out I realised in your source code you new up your template engine 2 ways, one brand new, or one taking in the jquery template engine as an argument.

If I remove jquery template (jquery.tmpl) from my project the templateUrl and other overrides in the data-bind work perfectly. Unfortunately I dont have an isolated test case to show this on the computer I am currently on, so will try and post one up tomorrow, but incase you know off the top of your head why this may be an issue thought I would post it.

**Comment by ifandelse** [comment]
Ah - I could see how this is happening.  you are correct In the code, I am detecting if jquery-tmpl is present, and - if so - I new up the external template engine where it takes the jquery template engine as an argument.  Otherwise, it gets new-ed up with the native KO template engine.  I have a note on the plugin's README that indicates that trying to override the url metadata in a binding won't work with jquery-templates because the KO source code does not pass the template options internally to where it could be used.  This could be a dangerous assumption to make on my part, if your project is truly using both native KO templates, but also use jquery templates for other things (though I assume you aren't using both jquery and KO native templates with KO at the same time, since I don't think that's possible without writing a custom template engine).  If this bit of auto-detection is causing you grief, I'd be happy to pull it out and just update the README to explain how you new it up for jquery-tmpl vs native templates.

**Comment by grofit** [comment]
I dont know how the innards of it are dealt with but all I was originally doing was including query.tmpl.js and apparently that automatically hooks into knockoutJS. As I was originally using the jquery template syntax on certain views, but for the most part it can be moved to purely use native data-binds. 

I am not doing anything specific with the template engines, purely load in knockout, the jquery.tmpl file, then the mapping extension and the externaltemplate extension.

Anyway I have managed to work around this restriction, but hopefully it can help others if they have the same problem. I will leave you to close this but as far as I am concerned if Knockout isn't passing you the data you need, not much you can do about this, so I am happy for it to be closed.

**Comment by ifandelse** [comment]
Thanks for the update - glad you found a workaround.  Keep me posted if, in the future, you would prefer I remove the auto-detection of jquery-tmpl out of the external template plugin.  Thanks!
