### ISSUE TITLE
a synchronous way to load templates

### ISSUE THREAD

**Issue by brandonwittwer** [ifandelse/Knockout.js-External-Template-Engine#15]
If I need to access a template directly after applying bindings, the template will not have time to render yet and will still show the loading template.  

Can you find an easy way to get the engine to use a synchronous method to load the html into the dom element? Skipping over the "loading..." template and waiting for the true template to be loaded?

**Comment by brandonwittwer** [comment]
I tried changing getTemplate in the engine to load using infuser's getSync method.  It runs, but the ajax call returns into the error callback.  

   getTemplate: function() {
                    //var self = this;
  //var self = this;

```
        //   infuser.get(self.options, function(tmpl) {
        //            self.data("precompiled",null);
        //            self.template(tmpl);
        //            self.loaded = true;
        //        });
                var tmpl=infuser.getSync(this.options);
                this.data("precompiled",null);
                this.template(tmpl);
                this.loaded = true;
```

**Strange thing is**, I'm getting a full response object in the callback:
The exception.responseText _is the downloaded template_, exception.status of 200 and "OK" for exception.statusText.  So it **worked**, but for some reason is coming back in the error handler.

**Comment by rniemeyer** [comment]
You can set this prior to calling applyBindings:

`infuser.defaults.ajax.async = false;`

**Comment by brandonwittwer** [comment]
Could it be so simple??  I'll find out by Monday and report back.

**Comment by ifandelse** [comment]
@bsingin64 - you really want to avoid synchronous requests at all costs, since they will block the event loop on which all other js runs in your browser.  I think what you may be looking for are the `afterRender` and `afterAdd` callbacks that Knockout.js provides for you (see [this](http://knockoutjs.com/documentation/template-binding.html#note_3_using_afterrender_afteradd_and_beforeremove)).  I updated the "native" example in this project to use an afterRender handler when rendering cities - check out the code in the [main.js file](https://github.com/ifandelse/Knockout.js-External-Template-Engine/blob/master/example/native/js/main.js), and also the template binding in [this file](https://github.com/ifandelse/Knockout.js-External-Template-Engine/blob/master/example/native/templates/view.html).

I hope that helps!  Also, you can disable the loading template by setting infuser's options.  For example:

`infuser.defaults.useLoadingTemplate = false;`

**Comment by ifandelse** [comment]
@bsingin64 What @rniemeyer said should work as well, though I would still urge you to avoid synchronous requests, especially since the hooks are there for you to execute code once the template has been rendered.  The getSync call in infuser is deprecated at this point, and will eventually go away....

**Comment by rniemeyer** [comment]
Definitely agree.  Sync should be the last resort.  Perhaps with more details, we can help with an alternative (`afterRender` or a custom binding).

**Comment by brandonwittwer** [comment]
I thought about afterRender there at the end before posing the question.  Figured I'd ask since it looked like the getsync was in there.

That "more information" you were asking for: after applyBinding runs I immediately was grabbing the root element of the template and created a jqueryUI dialog from it.

  Immediately after that, I deleted the original node (since jqueryUI puts the new dialog elements in the root of the body element, along with all my bindings, the original node is just an empty shell) (I know, kinda weird, but it let's me clean up modal dialogs that own their own viewmodel really well)

Anyhow, I was having trouble because the template didnt have that root element I was looking for in order to create that dialog from.

Looking forward to seeing the after render thing work, there are other steps I'm doing that would make sense to put there as well now that I think about it.

Thanks for both your input!!

**Comment by ifandelse** [comment]
@bsingin64 No problem!  Keep us posted if you have any other questions or issues.  Hope everything comes together well in your project!

**Comment by rniemeyer** [comment]
@bsingin64 you might want to consider using a custom binding for your jQuery UI dialog.  Here is a sample: http://jsfiddle.net/rniemeyer/SnPdE/.

**Comment by brandonwittwer** [comment]
Jim, Ryan, 

Thanks for your help here.  '''infuser.defaults.ajax.async = false;''' worked perfectly.  I will investigate mounting my jqueryUI dialog in the custom binding you mentioned.  I'm using the mediator principal as described in http://blog.monnet-usa.com/?p=404  So I'm trying to keep my Dom / Jquery interactions out of the model / templates if at all possible.  

Again, thanks so much.  Great work, both of you.  Seriously, Great Stuff!
