### ISSUE TITLE
RequireJS

### ISSUE THREAD

**Issue by sgentile** [ifandelse/Knockout.js-External-Template-Engine#21]
https://github.com/ifandelse/Knockout.js-External-Template-Engine/issues/8

In your comment you mention requirejs with knockoutjs community:  one of the reasons for this is because cool features like your code here seems to not want to adopt it, leaving the 'community' left with half-baked google solutions  :)

Please reconsider, knockoutjs and requirejs could be as good together as chocolate and peanut butter  :)

**Comment by ifandelse** [comment]
@sgentile I have no doubt that KO and require can work well together as I've seen it in action.  However, if you're using requirejs, you have a host of additional functionality (text loader plugin, ability to optimize templates inline with your 'built' JavaScript modules, etc.) that would seem to render this plugin obsolete, hence why I haven't bothered to include an AMD wrapper for this project.  In addition, requirejs 2.0 and higher allows you to 'shim' non AMD modules so that they play well with your AMD modules - and I'm assuming that shimming KO and this plugin lib is possible based on my experience shimming other non-AMD libs.  I have a number of other OSS projects getting the majority of my attention, so if you'd like to submit a PR including an conditional AMD wrapper, by all means, please do.

**Comment by sgentile** [comment]
that make sense - and I definitely appreciate your work on this.  I'm in process of trying to determine the best approach to take with more complex spa knockoutjs applications (multiple loading of views, navigation support, back button support, on demand template loading, etc..).  

Thanks for the feedback.

**Comment by ifandelse** [comment]
no problem!  I wrote the original version of this plugin back in my pre-AMD days, and still support it as much as I can to help out devs that don't have the AMD/requirejs option. I think Ryan Niemeyer has done some work loading KO templates via requirejs - might be worth checking his [blog](http://www.knockmeout.net/) out.

**Comment by genereddick** [comment]
I am using requirejs and both knockout and external-template-engine together as amd modules without any problem. What issues have people been running into?

**Comment by stevies** [comment]
I have it working also.  See:  https://github.com/stevies/ExampleRequireJS.git

**Comment by sgentile** [comment]
ok  - nice - I didn't realize it was possible - I will check it out - thanks for the sample to review!

**Comment by mg1075** [comment]
Highly relevant article by Ryan Niemeyer on external templates that @ifandelse has already commented on: 
http://blog.safaribooksonline.com/2014/01/31/using-external-templates-knockout-js/

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
