### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource.

### ISSUE THREAD

**Issue by SlavkoPar** [ifandelse/Knockout.js-External-Template-Engine#32]
When i run the Index.htm inside of Web Server it is OK.
When i run it from file system i get the message:
"No 'Access-Control-Allow-Origin' header is present on the requested resource."

I use: jquery-2.0.3.js
Your demo works because you use: jquery-1.7.1.js

No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'null' is therefore not allowed access.

Can we set some option for XMLHttpRequest for  Cross Domain Resource Sharing?

**Comment by ifandelse** [comment]
@SlavkoPar Why do you need to run this from the file system? Most browsers (Chrome especially, IIRC), have tight same-origin restrictions for files loaded from the file system. Typically, you'd run a web server locally to serve the files rather than load from the file system - at least then you'd actually have the option of adding the correct CORS headers if the files were loaded from a different web server than what the requesting page was loaded from.

**Comment by SlavkoPar** [comment]
Thanks for fast response. Actually i don't need it.
I put some article:
http://www.codeproject.com/Articles/706114/CRUD-with-Knockout-js-and-Templates-everywhere
http://jsfiddle.net/SlavkoPar/ZdZ93/ 

I was affraid that users will download the source and try it from file system
https://github.com/SlavkoPar/KnockoutCRUD  

Another  thing.
I use afterRender and i catch event "loading template", but i am more intereted in "loaded".
But i can explain it in detail if you are interested.

**Comment by ifandelse** [comment]
My apologies - this project has been retired. I wish had the bandwidth to keep up, but alas, I do not. You can read more [here](http://ifandelse.com/know-when-to-walk-away/). I'm open to transferring it to anyone that really wants it.
