### ISSUE TITLE
Nested templates are sometimes not working

### ISSUE THREAD

**Issue by flyingmutant** [ifandelse/Knockout.js-External-Template-Engine#4]
In case I have an external template, which contains nested template (defined in the same file) used with foreach binding, then $data inside the nested template is wrong.

Moving the definition of the nested template to the original .html file fixes the problem.

**Comment by ifandelse** [comment]
Hi there.  I assume the nested template is being defined inside a script block in the parent template's file?  This KO plugin wasn't designed to handle that scenario, and the reason is that KO core wouldn't actually support it if external templates were supported out of the box.  KO core's code simply looks for a template defined in a script block in the html file.  So if you have nested templates the traditional way, then KO core will look for the two script blocks that correspond to the template names.  My plugin extends the "template lookup" functionality to allow KO to reach back to the server and pull a template down that wasn't delivered with the original request.  It then adds it to the DOM (so now the script block exists in the document), and let's KO core continue doing the functionality it normally does as if the template had always existed in a script block.  That being the case, if you defined a template inside another external template, KO - and my plugin - is not going to know how to find it.  Since your external template file is ultimately placed inside a script block in the DOM by my plugin, neither KO nor my plugin will traverse the contents of that script block, looking for more templates since templates are expected to be accessed by finding a script block with the same name, etc.  The solution would be to segregate all your templates either by placing them in their own external files (which I would recommend), or by placing them in script blocks in the original html file.  Of course, it's possible to pull the templates down asynchronously via some other method (script loader, etc.), but that introduces another dependency and also breaks the means by which KO expects to locate/evaluate templates.  I hope that explanation helps!

**Comment by flyingmutant** [comment]
OK, thanks for the explanation. The weird thing was that _sometimes_, it worked, and sometimes — not.

**Comment by ifandelse** [comment]
Yeah - that is strange that it sometimes worked....gotta love the spooky bugs. :-)
