### ISSUE TITLE
Feature Request: Allow scripts to be parsed from template

### ISSUE THREAD

**Issue by engram-design** [ifandelse/Knockout.js-External-Template-Engine#7]
A really handy feature that would be great in keeping code modular is being able to include JS in your template (which would then be executed). Is this something remotely possible?

Great work on the KO 1.3 update too, been waiting patiently :)

**Comment by ifandelse** [comment]
Thanks for your patience on me getting this thing updated!  I don't believe KO could support the execution of SCRIPT elements embedded in a remote template, since I'm about 99.9% certain they would ignored (since the template itself is never attached to the DOM as-is, any embedded SCRIPT elements would never be attached to the DOM and evaluated).  What kind of use-case are you solving for?  I'm wondering if a script loader (or module system) might be able to help out if you're needing to pull js down on-demand....

**Comment by engram-design** [comment]
I thought that might be the case, as any script in the template is seemingly being ignored. 

I'm actually dynamically loading widgets onto a dashboard-type page. Each widget does something different (one might show some charts, one might be just plain text), and as such have their own JS and CSS specifically for that widget. In the past, i've just loaded all the JS and CSS for ALL the widgets on page load, which isn't the best solution (a user could remove all but one widget, but would still be using the JS for other, unused widgets). CSS is working fine being embedded in the templates.

I'm actually using Infuser to dynamically load pages (which works awesome by the way!), and that works exactly as I need (with embedded JS and CSS). The tricky part there is hooking it up to KO, as the widget templates are actually nested in Infuser templates.

To illustrate...
Dashboard (index.html) is opened by user. User clicks button, Page 1 is loaded by Infuser, and applyBindings() is called to setup KO bindings. Page 1 contains 4 widgets, which are templates in themselves and need to be loaded (somehow).

I'm happy to throw together an example app if that helps! It's quite possible i'm going about this the wrong way...

EDIT: After a little tinkering, i've ditched the KO-External-Template_engine and gone for just Infuser. I think i've got a pretty good working example here - http://github.com/engram-design/ko-templating-test. The only thing left it to make sure the widgets have proper context, which they don't at the moment. But that's probably more of an issue with KO than anything else. Sorry to waste your time!

**Comment by ifandelse** [comment]
No need to apologize - you're not wasting my time!  I really appreciate the feedback.  I think the problem you're solving highlights one of the areas that I have some complaints with KO - structuring a modular and decoupled application, flying in resources asynchronously as they are needed, gets problematic, as the core architecture seems to make some key assumptions in the other direction.  I looked at your sample app, and what you're doing makes sense to me.  Depending on the usefulness of it (or not), you could do the same approach with infuser.infuse() and take advantage of transition animations/fade-ins, etc.  Good luck!  I'll definitely be interested to hear how it turns out.

**Comment by engram-design** [comment]
Thanks for your help on this, i'll probably use infuse() down the track to pretty things up! It's a great project by the way, really liking the caching it does with loaded resources.

The way i've got it working now (which is possibly the worst way imaginable), is to directly inject a data-bind attribute on the loaded widget, to give it the corresponding widget from the viewModel (check example.html, line 17). If there is a better way to do this...

Awesome work on Infuser, TrafficCop and KO-External-Template, they are awesome!
