### ISSUE TITLE
Working with requirejs

### ISSUE THREAD

**Issue by baio** [ifandelse/Knockout.js-External-Template-Engine#8]
Hi! I wander it would be really cool if plugin works with requirejs instead of current dependencies. It even could be usefull without ko. Now I'm really bewildered, which one to use, your or https://github.com/SlexAxton/require-handlebars-plugin.

**Comment by ifandelse** [comment]
Unfortunately, I don't have any current plans to integrate require.js into this plugin, since infuser is already covering the functionality I need (and since the current KO ecosystem isn't really oriented towards amd-loader-style architecture (though I am a fan of require.js!).  You are more than welcome to fork and implement if you want.  The KO-oriented code is very decoupled from infuser, only the "getTemplate" call in the template source references it, so switching it out with another implementation that retrieves the content wouldn't be difficult.

Regarding your concern on whether to use this plugin vs. Alex Sexton's, all I can say is that I think Alex is a tremendously awesome developer, and if you're not using Knockout.js, go with his, since this plugin is specifically focused on extending Knockout's template loading process.  "Infuser", however (one of the deps in this plugin), is stand-alone, and could be used to do something similar to Alex's plugin.  However, if you really want to use require.js, Alex's project is already there. :-)
