### ISSUE TITLE
Template path

### ISSUE THREAD

**Issue by baio** [ifandelse/Knockout.js-External-Template-Engine#9]
Hi. It would be nice if I could set template path directly in data binding. For exampl - data-bind="template : '/App/Templates/Template".

Cheers!

**Comment by ifandelse** [comment]
I'll try and look at this in the next couple of weeks, once some other projects calm down.  I do see how that could be useful.  One thing is I'm not sure if it will require a custom template binding....we shall see.

**Comment by baio** [comment]
Nice to hear!

**Comment by wforney** [comment]
It might be good to note also that you can't use templates on a different domain than your site.

**Comment by ifandelse** [comment]
@wforney - I would hope most web developers know about typical same-origin restrictions in a browser.  I definitely do not have any plans to bake in CORS support.

**Comment by wforney** [comment]
True, but this is the kind of thing that would be handy to have CORS support. I wouldn't expect this plugin to have it though as that's a bigger issue than this addresses.

**Comment by grofit** [comment]
I had to implement something like this for my current project as I required to be able to load templates from multiple locations, rather than dirty the template name, I just added a location to a custom binding (as you may not know the path in the markup for larger projects, as they may be generated at runtime or populated from an Ajax request...) and then delagated the call through to the normal template mechanism. 

So this way much like you do the setup for koExternalTemplateEngine you would also setup this other component setting up locations. I would much rather see support for this included within the template engine but you can still get around it, although in the new version there are some problems with templates within templates using this current implementation... 

Anyway here is a stackoverflow post on the subject and the solution (although I edited it quite a bit to get it working properly).

http://stackoverflow.com/questions/8158408/how-do-i-add-custom-data-bindings-to-knockoutjs-template-binding

**Comment by jamesfoster** [comment]
@ifendelse I've just come across this same issue. I'd like various templates on the page to use different template paths.

after looking at the code it seems that the binding context isn't passed in to makeTemplateSource

https://github.com/SteveSanderson/knockout/blob/master/src/templating/templateEngine.js#L52

so, step 1, override renderTemplate

```
engine.renderTemplate = function (template, bindingContext, options) {
    var templateSource = engine.makeTemplateSource(template, bindingContext, options);
    return engine.renderTemplateSource(templateSource, bindingContext, options);
};
```

then you can pass `options` to the `ExternalTemplateSource` object

```
engine.templates[template] = new ExternalTemplateSource(template, options);
```

now if your markup contains:

```
<ul data-bind="template: { name: 'bar', templateUrl: 'foo' }"></ul>
```

you can use `options.templateUrl` to override the default. You then just need to override those options in infuser for that template. To make it easier you could wrap the infuser options in an object and just pass that to infuser:

```
<ul data-bind="template: { name: 'bar', infuser: { templateUrl: 'foo', templateSuffix: '.tmpl' } }"></ul>
```

**Comment by ifandelse** [comment]
Ok - I really hope to carve some time out this weekend to take care of this now that life has calmed down (new job, getting ready to move, etc.)...sorry for the delay.

**Comment by ifandelse** [comment]
I've added support for adding overrides to any of infuser's options within the template binding.  For example, you can write `<div data-bind="template: { name: 'stats', templateUrl: 'templates/info'}"></div>` in a binding to override the default url (folder) that infuser will look to find the template.  Any option infuser.get() takes can be included:
- `templateUrl` (dir where the template resides)
- `templateSuffix`
- `templatePrefix`
- `dataType` (used in the $.ajax request - defaults to "html"
- `type` (HTTP method, defaults to "GET")

This is only supported in **native** templates.  The jquery-tmpl engine in KO does not pass the "options" argument beyond the `executeTemplate` call.  I've pinged one of the KO team to ask about this, and might submit a pull request to change that if it looks like they might merge it.  jquery-tmpl is no longer supported, though, so I doubt I will add support for it outside of the KO team changing the codebase to pass the options on through to `makeTemplateSource` and `renderTemplate`.....

**Comment by jamesfoster** [comment]
Glad I could help with this. After a second look a few days ago I too noticed there were several calls to `makeTamplateSource` in knockout which unfortunately breaks this approach for other template engines. Hopefully the KO team will see the benefit of this change.

I did realise something else just now. The following 2 bindings will both render the same template.

```
<div data-bind="template: { name: 'baz', templateUrl: 'foo'}"></div>
<div data-bind="template: { name: 'baz', templateUrl: 'bar'}"></div>
```

Perhaps templates should be cached by url instead of template name? However, this seems like a more fundamental change to infuser.

**Comment by ifandelse** [comment]
@jamesfoster you are exactly right, thanks for catching that for me since I probably wouldn't have noticed for a day or two at least!  I've updated infuser so that templates are cached by url.  In addition, I've moved ajax options from infuser.defaults to infuser.defaults.ajax, so you can still pass ajax options in the template binding, but it would look something like this:

`<div data-bind="template: { name: 'baz', templateUrl: 'foo', ajax: { cache: false } }"></div>`

**Comment by ifandelse** [comment]
@jamesfoster I also meant to include a big thanks for providing the code snippets and your feedback on this!

**Comment by jamesfoster** [comment]
No problem. This is a great project. A lot of thought and effort has gone into it with traffic cop and infuser. I'm more than happy to help out.

**Comment by baio** [comment]
awesome!

**Comment by grofit** [comment]
I am still receiving the problem like jamesfoster, where I have 3 templates which have 2 different templateUrl values, however for some reason it seems to overwrite what I put in.

I set a default when the site loads in a config file:

infuser.defaults.templateUrl = ModuleConfiguration.templateLocations.main; // being something like "/modules/main/templates/"
infuser.defaults.templateSuffix = ".template.html";

Then every other call uses the templateUrl override in the data-bind, however it seems that they ignore it. However if I take out the default setting shown above they dont seem to use any templateUrl. I am pretty sure I am on the latest version, or at least the version which contains your fixes above as it is infuser.defaults not infuser.config.

Here is an example of a template call:

// Had to remove bracket or it wouldnt show, not used git much so dont know the hilighting options
div id="plugin-browser-template" class="with-background-color-3" data-bind="template: {name: 'plugin-browser', 
            templateUrl: ModuleConfiguration.templateLocations.shared }, visible: PluginBrowserVisibility()"></div>

However it ends up using whatever the default one is (main currently) or if I remove the default it just doesn't mother looking. 1 of the 3 templates is nested within one of the top 2 templates, I cannot see that causing any issues but nested templates are supported right?

**Comment by ifandelse** [comment]
Nested templates are definitely supported.  Are you using a variable reference as the templateUrl arg?  I'll try and put a sample project together to test this out... (Update: I wasn't sure the variable ref in the declarative binding would resolve correctly, but it appears to on my end)

**Comment by ifandelse** [comment]
@grofit - I've added a sample project [here](https://github.com/ifandelse/Knockout.js-External-Template-Engine/tree/master/example/native-nested-alt-locations).  You should be able to run that locally using node, or a local IIS/apache web server.  If you haven't already, I highly recommend running your project in Chrome and using the dev tools to look at the requests going to the server so you can verify that the right urls are being used in the requests.  An example of this can be seen [here](https://skitch.com/ashbylane/ghefa/knockout.js-native-external-templates-example).  I'm sure you've checked, but verify that your template Url values only start with a "/" if they truly begin at the root of your site.  The template Url is typically a relative path (relative to the html page making the request, via script, for the template) - you can use absolute paths if necessary, just be sure the url is correctly formed.

If you have an example project or code that I could look at/run I'd be happy to try and take a look to help get this resolved.  Thanks!

**Comment by grofit** [comment]
Will try and put something together, I am using a variable, and it is absolute not relative... its a large project and a lot of the content used by knockout is classed as a plugin, so there is a modules folder for each plugin, meaning each has its own configuration settings, and registers its template locations. Also to make matters more difficult the module directory could be anywhere, as there is a configuration value which sets its location, but as its all static files it could be hosted outside of the main app.

Anyway will try to isolate a test case today and get back to you.

**Comment by grofit** [comment]
So sorry, I meant to comment on this friday evening but I completely forgot... anyway I tried to isolate a test case, but I got none of the problems I mention above when running relative/absolute routes in simple page with just the required files.

It must be something strange happening within my framework, I am loading alot of the content with YepNope, and this comes in with that, but I cannot see how that could cause a problem, as if it wasn't loaded in time it would throw an error saying that infuser does not exist, not let me assign it and continue.

So anyway ignore the issue I have mentioned as I will assume until I can find out more that it is specific to my use-case/scenario.

**Comment by FacioRatio** [comment]
It would be handy if templateUrl was not merely an override, but could also be used to build on whatever is set as the detault templateUrl. For example:

infuser.defaults.templateUrl = "/Templates";

And then in my page:

div data-bind="template: { name: 'foo', data: x, templateUrl: 'foo' }"
div data-bind="template: { name: 'bar', data: y, templateUrl: 'bar' }"

Where neither 'foo' nor 'bar' have a leading slash. The complete templateUrl would be:

/Templates/foo/foo.tmpl.html
/Templates/bar/bar.tmpl.html

I would like to have each of my templates in their own subfolder so that I can group other assets with them, such as .css and -- more importantly -- their .js viewmodels.

**Comment by enzoaeneas** [comment]
Sorry to revived this; maybe it should be its own issue.
I too would like functionality like what is described by @FacioRatio, but without breaking the current functionality.
Maybe a convention on the template name could be used?

I may look up the code and try a few approaches myself.

**Comment by ifandelse** [comment]
@enzoaeneas I'm not opposed to merging something back in, if it makes sense - if you end up finding something that works in this case.  I've got a few other projects taking the lion's share of my time, so this one has been a bit neglected unfortunately....

**Comment by enzoaeneas** [comment]
Cool. I am looking at adding the following:
1. **namespace** option to the binding - the specified namespace would be appended to the templateUrl to form a new search path
2. **namespaceRoot** option to the main configuration. This will either be appended to templateUrl or used instead of it and then the **namespace** option is used.
